language: node_js
node_js:
- 9
script:
- node ./internals/scripts/generate-templates-for-linting
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_failure: change
after_success: npm run coveralls
cache:
  yarn: true
  directories:
  - node_modules
before_deploy:
- export PUBLIC_PATH="/every-hour/"
- export INDEX_TEMPLATE="app/ghPages.html"
- npm run build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  verbose: true
  on:
    branch: master