language: node_js
node_js:
- 8
script:
- node ./internals/scripts/generate-templates-for-linting
- npm run test
- npm run build
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_failure: change
after_success: npm run coveralls
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: script
  skip-cleanup: true
  script: bash ./deploy.sh
  on:
    branch: master
env:
  global:
  - ENCRYPTION_LABEL: "b83aabfe48b2"
  - COMMIT_AUTHOR_EMAIL: "mn2587@columbia.edu"